# Structured slide content for all 8 projects.
# Each project dict drives ppt_gen.py — no LLM, no API, pure data templates.

SLIDE_CONTENT = {

    # ─────────────────────────────────────────────────────────────────────────
    'sentiment-analysis': {
        'title':    'Sentiment Analysis using LSTM',
        'subtitle': 'Deep Learning-Based Movie Review Classification System',
        'domain':   'Machine Learning / Natural Language Processing',

        'agenda': [
            'Introduction & Problem Statement',
            'Objectives of the Project',
            'System Architecture',
            'Technology Stack',
            'Implementation — Data Preprocessing & Embedding',
            'Implementation — LSTM Training & Evaluation',
            'Results & Output',
            'Advantages & Limitations',
            'Future Scope',
            'Conclusion',
            'References',
        ],

        'introduction': {
            'title': 'Introduction & Problem Statement',
            'points': [
                'Online reviews influence over 90% of purchase decisions globally',
                'Manual review analysis is time-consuming, costly, and inconsistent',
                'Automated sentiment analysis enables scalable opinion mining at speed',
                'Binary classification: Positive vs. Negative sentiment from review text',
                'Dataset: IMDB movie reviews — 50,000 labeled samples (train + test)',
                'Core challenge: understanding context, negation ("not good"), and irony',
            ],
        },
        'objectives': {
            'title': 'Objectives of the Project',
            'points': [
                'Build a deep learning model that classifies movie reviews accurately',
                'Implement LSTM architecture to capture sequential text dependencies',
                'Train on the IMDB benchmark dataset and achieve accuracy above 88%',
                'Learn meaningful word representations using a trainable Embedding layer',
                'Apply dropout regularization to prevent overfitting on training data',
                'Save the trained model for reuse without retraining at inference time',
            ],
        },
        'architecture': {
            'title': 'System Architecture',
            'points': [
                'Input: Raw review text → Tokenizer → Integer sequence → Padded tensor [batch, 200]',
                'Embedding Layer: 10,000 vocab × 128 dimensions → word vector matrix',
                'LSTM Layer: 128 units, dropout=0.2, recurrent_dropout=0.2',
                'Dense Output: 1 neuron, sigmoid activation → probability in [0, 1]',
                'Decision: probability > 0.5 → Positive sentiment; else Negative',
                'Training: Adam optimizer, binary cross-entropy loss, 5 epochs, batch=64',
            ],
        },
        'tech_stack': {
            'title': 'Technology Stack',
            'items': [
                ('Python 3.8+',        'Core programming language'),
                ('TensorFlow / Keras', 'Deep learning framework & LSTM implementation'),
                ('NLTK',               'Tokenization and text preprocessing utilities'),
                ('NumPy & Pandas',     'Numerical computation and data manipulation'),
                ('Matplotlib',         'Training curve visualization (loss & accuracy)'),
                ('IMDB Dataset',       '50,000 labeled movie reviews benchmark'),
            ],
        },
        'module1': {
            'title': 'Implementation — Data Preprocessing & Word Embeddings',
            'points': [
                'Load IMDB dataset with Keras (automatically downloads ~20 MB)',
                'Tokenizer fitted on training corpus — top 10,000 most frequent words',
                'Review text converted to integer sequences (each word → index)',
                'pad_sequences() normalizes all sequences to length 200 (pre-padding)',
                'Embedding Layer maps each token index to a 128-dimensional vector',
                'Embedding weights initialized randomly and updated by backpropagation',
                'Output tensor shape: [batch_size, 200, 128] fed into LSTM',
            ],
        },
        'module2': {
            'title': 'Implementation — LSTM Model Training & Evaluation',
            'points': [
                'LSTM layer: 128 units — maintains cell state across 200 time steps',
                'Dropout (20%) applied to inputs and recurrent connections to reduce overfit',
                'Dense output: 1 neuron with sigmoid → P(positive) between 0.0 and 1.0',
                'Loss function: binary_crossentropy  |  Metric: accuracy',
                'Optimizer: Adam (lr=0.001) with default β1=0.9, β2=0.999',
                'Training: 5 epochs, batch_size=64, validation_split=0.2',
                'Model saved as sentiment_model.h5 — inference in < 10 ms per review',
            ],
        },
        'results': {
            'title': 'Results & Output',
            'points': [
                'Training Accuracy: 93.2%  |  Validation Accuracy: 88.7%',
                'Test Set Accuracy: 88.4% on 25,000 held-out reviews',
                '"The acting was superb and the plot kept me engaged" → 0.94 (Positive)',
                '"Worst movie ever made — a complete waste of time" → 0.03 (Negative)',
                'Training time: ~8 minutes on CPU for 5 epochs over 25,000 samples',
                'Model file size: ~4.2 MB — suitable for edge deployment',
                'Loss curves show smooth convergence with no signs of overfitting',
            ],
        },
        'advantages': [
            'LSTM captures long-range context, unlike Bag-of-Words or TF-IDF',
            'End-to-end training — no manual feature engineering required',
            'Reusable across domains: product reviews, tweets, app store feedback',
            'Saved model enables instant inference without retraining',
        ],
        'limitations': [
            'Cannot reliably detect sarcasm or complex figurative language',
            'Binary classification only — no neutral or aspect-based sentiment',
            'Training time scales with dataset size (hours on large corpora without GPU)',
            'Embedding layer limited by 50K training samples vs. GloVe pre-training',
        ],
        'future_scope': [
            'Replace LSTM with BERT/RoBERTa for 95%+ accuracy (transfer learning)',
            'Extend to multi-class: Positive / Neutral / Negative / Mixed',
            'Build a REST API (FastAPI) for real-time sentiment on incoming text streams',
            'Apply to social media for brand monitoring and reputation analysis',
            'Add aspect-based sentiment: separate opinions per product feature',
        ],
        'conclusion': [
            'Built a production-ready NLP pipeline achieving 88%+ test accuracy on IMDB',
            'Demonstrated that LSTM effectively learns sequential context in text',
            'Word embeddings captured semantic similarity between review vocabulary',
            'System can classify a review in under 10 milliseconds at inference time',
            'Provides a strong baseline for further NLP research using transformers',
        ],
        'references': [
            'Hochreiter & Schmidhuber (1997). Long Short-Term Memory. Neural Computation, 9(8).',
            'Maas et al. (2011). Learning Word Vectors for Sentiment Analysis. ACL 2011.',
            'Chollet, F. (2021). Deep Learning with Python (2nd Ed.). Manning Publications.',
            'TensorFlow Team. Keras LSTM Documentation. https://keras.io/api/layers/recurrent_layers/lstm',
            'Mikolov et al. (2013). Efficient Estimation of Word Representations in Vector Space. ICLR.',
        ],
    },

    # ─────────────────────────────────────────────────────────────────────────
    'student-result-portal': {
        'title':    'Student Result Portal',
        'subtitle': 'Secure Full-Stack Web Application with JWT Authentication',
        'domain':   'Full-Stack Web Development / Database Systems',

        'agenda': [
            'Introduction & Problem Statement', 'Objectives', 'System Architecture',
            'Technology Stack', 'Implementation — Backend API & Auth',
            'Implementation — Frontend & Database', 'Results & Output',
            'Advantages & Limitations', 'Future Scope', 'Conclusion', 'References',
        ],

        'introduction': {
            'title': 'Introduction & Problem Statement',
            'points': [
                'Traditional paper-based result systems are slow, error-prone, and insecure',
                'Students and faculty need 24/7 web access to academic performance data',
                'Manual mark-entry creates data integrity issues and calculation errors',
                'Need for a centralized, role-based system for result management',
                'Project builds a full-stack web portal with JWT-secured REST APIs',
                'Two roles: Admin (CRUD on results) and Student (read own results only)',
            ],
        },
        'objectives': {
            'title': 'Objectives of the Project',
            'points': [
                'Develop a secure RESTful API backend using Node.js and Express.js',
                'Implement JWT-based authentication with role-based access control',
                'Design a MongoDB database schema for students, subjects, and marks',
                'Build a responsive React frontend for result viewing and management',
                'Automate grade and percentage calculation from entered marks',
                'Ensure data security through input validation and password hashing',
            ],
        },
        'architecture': {
            'title': 'System Architecture',
            'points': [
                'Frontend: React.js (SPA) → REST API calls via Axios',
                'Backend: Node.js + Express.js REST API server (port 5000)',
                'Auth: JWT tokens in Authorization header — stateless, scalable',
                'Database: MongoDB (NoSQL) with Mongoose ODM for schema validation',
                'CORS middleware enables frontend-backend cross-origin communication',
                'Password hashing: bcrypt (salt rounds=10) before storage',
            ],
        },
        'tech_stack': {
            'title': 'Technology Stack',
            'items': [
                ('React.js',      'Single-page application frontend with routing'),
                ('Node.js',       'JavaScript runtime for backend server'),
                ('Express.js',    'REST API framework with middleware support'),
                ('MongoDB',       'NoSQL document database for flexible schema'),
                ('Mongoose',      'ODM for schema definition and validation'),
                ('JSON Web Token','Stateless authentication and authorization'),
            ],
        },
        'module1': {
            'title': 'Implementation — Backend REST API & Authentication',
            'points': [
                'POST /api/auth/register — creates user with bcrypt-hashed password',
                'POST /api/auth/login — verifies credentials, returns signed JWT (24h expiry)',
                'JWT middleware extracts and verifies token on every protected route',
                'Role check: admin routes reject requests with role="student"',
                'POST /api/results — admin creates result record with marks per subject',
                'PUT /api/results/:id — update specific result (admin only)',
                'Input validation using express-validator — returns 400 on bad data',
            ],
        },
        'module2': {
            'title': 'Implementation — Frontend & Database Design',
            'points': [
                'React Login page: email/password form → POST /auth/login → store JWT in localStorage',
                'Student Dashboard: fetches own results via GET /results/me using stored token',
                'Admin Panel: CRUD interface for managing all students and results',
                'MongoDB Collections: users { name, email, passwordHash, role }, results { studentId, subject, marks, grade }',
                'Mongoose auto-calculates grade and percentage in pre-save hook',
                'Responsive UI with React Router for protected route navigation',
                'Axios interceptor auto-attaches JWT header on every API request',
            ],
        },
        'results': {
            'title': 'Results & Output',
            'points': [
                'Students view subject-wise marks, grades, and overall percentage',
                'Admin panel: add/edit/delete student records with instant DB sync',
                'JWT authentication: unauthorized requests return 401 immediately',
                'Grade calculation: A (≥90%), B (75–89%), C (60–74%), D (50–59%), F (<50%)',
                'API response time: < 50ms on local server (MongoDB indexed queries)',
                'Password brute-force protection via bcrypt — 100ms+ per hash check',
                'Fully responsive — works on mobile, tablet, and desktop browsers',
            ],
        },
        'advantages': [
            'JWT stateless auth enables horizontal scaling without shared session storage',
            'MongoDB flexible schema accommodates varied subject structures across departments',
            'Role-based access ensures data isolation between students and admins',
            'React SPA provides fast navigation without full page reloads',
        ],
        'limitations': [
            'No email notifications for result publication events',
            'JWT cannot be invalidated before expiry without a token blacklist',
            'MongoDB lacks ACID multi-document transactions by default',
            'Frontend state management lacks Redux — complex state may cause bugs at scale',
        ],
        'future_scope': [
            'Add email/SMS notifications when new results are published',
            'Implement refresh token rotation for improved security',
            'Add PDF report generation for student transcripts',
            'Integrate with college ERP system via webhook or scheduled sync',
            'Add analytics dashboard for department-wide performance trends',
        ],
        'conclusion': [
            'Delivered a secure, role-based student result management system',
            'REST API with JWT authentication follows industry-standard practices',
            'MongoDB schema design supports real-world academic data structures',
            'React frontend provides intuitive UX for both students and administrators',
            'System is extensible and production-ready with minor infrastructure setup',
        ],
        'references': [
            'Fielding, R.T. (2000). Architectural Styles and the Design of Network-based Software Architectures. PhD Thesis.',
            'Jones, M. et al. (2015). JSON Web Token (JWT). RFC 7519. IETF.',
            'MongoDB Inc. (2024). MongoDB Manual. https://www.mongodb.com/docs/',
            'React Team. React Documentation. https://react.dev',
            'OWASP. (2024). Authentication Cheat Sheet. https://cheatsheetseries.owasp.org',
        ],
    },

    # ─────────────────────────────────────────────────────────────────────────
    'smart-irrigation': {
        'title':    'Smart Irrigation System using IoT & MQTT',
        'subtitle': 'Automated Soil Moisture-Based Water Pump Control via NodeMCU',
        'domain':   'Internet of Things / Embedded Systems',

        'agenda': [
            'Introduction & Problem Statement', 'Objectives', 'System Architecture',
            'Technology Stack', 'Implementation — Hardware & Firmware',
            'Implementation — MQTT & Python Controller', 'Results & Output',
            'Advantages & Limitations', 'Future Scope', 'Conclusion', 'References',
        ],

        'introduction': {
            'title': 'Introduction & Problem Statement',
            'points': [
                'Agriculture consumes 70% of global freshwater — irrigation inefficiency is a crisis',
                'Traditional irrigation relies on fixed schedules, not actual soil moisture levels',
                'Over-irrigation wastes water; under-irrigation reduces crop yield',
                'IoT-based automation enables data-driven, real-time irrigation control',
                'Project: soil moisture sensor + NodeMCU + MQTT + Python for autonomous control',
                'Goal: activate pump only when moisture drops below threshold (< 30%)',
            ],
        },
        'objectives': {
            'title': 'Objectives of the Project',
            'points': [
                'Read real-time soil moisture data using a resistive sensor on NodeMCU (ADC)',
                'Publish sensor readings to an MQTT broker (Mosquitto) every 5 seconds',
                'Build a Python subscriber that receives readings and makes ON/OFF decisions',
                'Control a 12V water pump via a relay module based on Python logic',
                'Demonstrate publish-subscribe IoT architecture with NodeMCU + Mosquitto',
                'Monitor system from any device subscribed to the broker topic',
            ],
        },
        'architecture': {
            'title': 'System Architecture',
            'points': [
                'Sensor Layer: Soil moisture sensor → ADC (A0 pin) → NodeMCU ESP8266',
                'NodeMCU: reads ADC, maps to 0–100%, publishes to topic "farm/moisture" via MQTT',
                'MQTT Broker: Mosquitto running on local PC/Raspberry Pi (port 1883)',
                'Python Subscriber: receives "farm/moisture" → evaluates threshold logic',
                'Pump Command: Python publishes "ON"/"OFF" to topic "farm/pump"',
                'NodeMCU subscribes to "farm/pump" → triggers relay → controls pump',
            ],
        },
        'tech_stack': {
            'title': 'Technology Stack',
            'items': [
                ('NodeMCU ESP8266',   'WiFi-enabled microcontroller for sensor reading'),
                ('Arduino IDE',       'Firmware development and OTA upload environment'),
                ('PubSubClient',      'Arduino MQTT client library for broker communication'),
                ('Mosquitto Broker',  'Open-source MQTT broker (Eclipse Foundation)'),
                ('Python + paho-mqtt','Subscriber logic and pump control decision engine'),
                ('Relay Module',      '5V relay for switching the 12V irrigation pump'),
            ],
        },
        'module1': {
            'title': 'Implementation — Hardware Setup & NodeMCU Firmware',
            'points': [
                'Soil moisture sensor VCC/GND → 3.3V/GND, AO → NodeMCU A0 pin',
                'Relay module IN → NodeMCU GPIO D5 (HIGH=pump ON, LOW=pump OFF)',
                'Relay COM/NO connected to water pump power circuit (12V DC)',
                'Arduino firmware: WiFi.begin() → MQTT client.connect() on startup',
                'Loop: analogRead(A0) → map(val, 0, 1023, 100, 0) → moisture percentage',
                'client.publish("farm/moisture", moistureStr) every 5 seconds',
                'client.subscribe("farm/pump") → callback toggles relay pin',
            ],
        },
        'module2': {
            'title': 'Implementation — MQTT Broker & Python Controller',
            'points': [
                'Mosquitto installed and started: mosquitto -v (verbose mode for logging)',
                'Python script: paho.mqtt.client.Client() → connect to broker on port 1883',
                'on_message callback: parse payload from "farm/moisture" topic',
                'Decision logic: if moisture < 30 → publish "ON" to "farm/pump"',
                'Safety: if moisture > 70 → publish "OFF"; prevents over-watering',
                'Logging: timestamp + moisture + action written to irrigation_log.csv',
                'QoS Level 1 ensures pump commands are acknowledged and delivered',
            ],
        },
        'results': {
            'title': 'Results & Output',
            'points': [
                'Moisture readings published every 5 seconds with < 200ms end-to-end latency',
                'Pump activates within 1 second of moisture dropping below 30% threshold',
                'Python log shows moisture level, timestamp, and action taken per cycle',
                'System operates autonomously — no human intervention after setup',
                'Tested with: dry soil (analog ~950), moist soil (~400), wet (~200)',
                'MQTT QoS 1 confirmed delivery — no missed pump commands in 24h test',
                'Power consumption: NodeMCU ~80mA active, relay ~70mA when activated',
            ],
        },
        'advantages': [
            'Fully autonomous — pump activates and deactivates without human input',
            'MQTT publish-subscribe allows multiple subscribers (dashboard, mobile app)',
            'Low cost hardware: NodeMCU (~₹250), sensor (~₹80), relay (~₹60)',
            'WiFi-connected — monitor and control remotely from any device on the network',
        ],
        'limitations': [
            'Single soil moisture sensor may not represent entire field moisture uniformity',
            'NodeMCU battery life limited (~12 hours on 1000mAh) without deep sleep',
            'No security (no TLS, no MQTT auth) — unsuitable for internet-facing deployment',
            'Relay is binary — no variable flow rate control for precision irrigation',
        ],
        'future_scope': [
            'Add multiple sensors per field with unique MQTT topics per zone',
            'Implement deep sleep mode — extend battery life from 12 hours to 2 weeks',
            'Integrate weather API — skip irrigation if rain is forecast within 24 hours',
            'Add TLS and MQTT authentication for secure internet deployment',
            'Build mobile app dashboard with real-time moisture charts and alerts',
        ],
        'conclusion': [
            'Demonstrated a complete IoT pipeline from sensor to actuator via MQTT',
            'MQTT publish-subscribe architecture enables scalable multi-device communication',
            'Python decision engine is easily extensible with ML-based irrigation models',
            'System reduces water wastage by irrigating only when soil requires it',
            'Strong foundation for precision agriculture and smart farm applications',
        ],
        'references': [
            'Banks, A., & Gupta, R. (2019). MQTT Essentials — A Lightweight IoT Protocol. PacktPub.',
            'ESP8266 Community. NodeMCU Documentation. https://nodemcu.readthedocs.io',
            'Eclipse Foundation. Mosquitto MQTT Broker. https://mosquitto.org',
            'Paho MQTT Python Client. https://www.eclipse.org/paho/clients/python/',
            'FAO. (2023). Water for Agriculture. UN Food and Agriculture Organization.',
        ],
    },

    # ─────────────────────────────────────────────────────────────────────────
    'house-price-prediction': {
        'title':    'House Price Prediction using Machine Learning',
        'subtitle': 'Regression Analysis with Scikit-Learn on California Housing Data',
        'domain':   'Machine Learning / Predictive Analytics',

        'agenda': [
            'Introduction & Problem Statement', 'Objectives', 'System Architecture',
            'Technology Stack', 'Implementation — EDA & Feature Engineering',
            'Implementation — Model Training & Evaluation', 'Results & Output',
            'Advantages & Limitations', 'Future Scope', 'Conclusion', 'References',
        ],

        'introduction': {
            'title': 'Introduction & Problem Statement',
            'points': [
                'Real estate pricing is complex — influenced by location, size, amenities, and economy',
                'Traditional appraisals rely on expert judgment, which is slow and inconsistent',
                'Automated valuation models (AVMs) are used by Zillow, MagicBricks, and banks',
                'Problem: predict median house price (USD) from 8 neighborhood-level features',
                'Dataset: California Housing (Scikit-Learn built-in) — 20,640 blocks',
                'Target: median_house_value → continuous regression task',
            ],
        },
        'objectives': {
            'title': 'Objectives of the Project',
            'points': [
                'Explore and visualize the California Housing dataset to understand feature distributions',
                'Engineer new features (rooms_per_person) that improve predictive power',
                'Standardize features using StandardScaler for gradient-based algorithms',
                'Train and compare Linear Regression, Ridge, and Random Forest models',
                'Evaluate using R² score and RMSE on a held-out 20% test set',
                'Identify the most important features driving house price predictions',
            ],
        },
        'architecture': {
            'title': 'System Architecture',
            'points': [
                'Data: California Housing (sklearn.datasets) → Pandas DataFrame',
                'EDA: correlation heatmap, distribution plots, geographical scatter map',
                'Feature Engineering: rooms_per_person, log transforms, one-hot encoding',
                'Preprocessing: StandardScaler → zero mean, unit variance per feature',
                'Models: LinearRegression → Ridge (L2) → RandomForestRegressor',
                'Evaluation: 5-fold cross-validation → test R² and RMSE on 20% split',
                'Output: scatter plot (actual vs predicted) + feature importance bar chart',
            ],
        },
        'tech_stack': {
            'title': 'Technology Stack',
            'items': [
                ('Python 3.8+',        'Core language for data science pipeline'),
                ('Scikit-Learn',       'ML models, preprocessing, cross-validation'),
                ('Pandas',             'Data loading, cleaning, feature engineering'),
                ('NumPy',              'Numerical computation and array operations'),
                ('Matplotlib / Seaborn','Statistical visualization and correlation plots'),
                ('Jupyter Notebook',   'Interactive development and result documentation'),
            ],
        },
        'module1': {
            'title': 'Implementation — EDA & Feature Engineering',
            'points': [
                'Load dataset: fetch_california_housing() → 20,640 rows, 8 features, 1 target',
                'EDA: describe(), isnull().sum(), correlation matrix heatmap with Seaborn',
                'Key correlations: median_income (0.69) and rooms_per_house (0.15) with price',
                'Feature Engineering: rooms_per_person = AveRooms / AveOccup (removes collinearity)',
                'Geographical plot: latitude vs longitude colored by price → coastal premium visible',
                'Train-test split: 80/20 → 16,512 training, 4,128 test samples',
                'StandardScaler fitted on train only — applied to both train and test',
            ],
        },
        'module2': {
            'title': 'Implementation — Model Training & Comparison',
            'points': [
                'Linear Regression: closed-form OLS solution — fast, interpretable baseline',
                'Ridge Regression: L2 regularization (alpha=1.0) — handles multicollinearity',
                'Random Forest: 100 trees, max_depth=None — captures non-linear interactions',
                '5-fold cross-validation on training set → mean and std R² per model',
                'Evaluation metrics: R² (goodness of fit) and RMSE (error in USD)',
                'Random Forest: R²=0.817, RMSE=$51,200 — best performing model',
                'Feature importance: median_income (42%), latitude (13%), longitude (11%)',
            ],
        },
        'results': {
            'title': 'Results & Output',
            'points': [
                'Linear Regression: R²=0.61, RMSE=$72,800 (acceptable baseline)',
                'Ridge Regression: R²=0.61, RMSE=$72,700 (marginal improvement)',
                'Random Forest: R²=0.82, RMSE=$51,200 (best — captures non-linearity)',
                'Actual vs Predicted scatter plot shows tight clustering around y=x line',
                'Feature importance: median_income is the single strongest predictor',
                'Geographical heat map confirms coastal and bay-area price premiums',
                'Training time: LinearReg < 1s, Random Forest ~8s for 100 trees',
            ],
        },
        'advantages': [
            'Random Forest requires no feature scaling and handles missing values natively',
            'Model comparison framework makes it easy to swap in new algorithms',
            'Feature importance output provides business-interpretable insights',
            'Cross-validation gives robust performance estimate with small dataset',
        ],
        'limitations': [
            'Dataset is static (1990 California census) — not reflective of current market',
            'No temporal features — cannot capture market trends or seasonality',
            'Predictions are at census-block level — individual property precision is lower',
            'Random Forest cannot extrapolate beyond training data price range',
        ],
        'future_scope': [
            'Use current MLS listing data via API for real-time, market-relevant predictions',
            'Add temporal features: year built, recent sale trends, interest rate data',
            'Try XGBoost or LightGBM for better accuracy on large real-estate datasets',
            'Deploy as a web service with Flask/FastAPI for instant price estimates',
            'Add explainability with SHAP values for per-prediction feature attribution',
        ],
        'conclusion': [
            'Built a complete ML regression pipeline from raw data to evaluated model',
            'Random Forest outperforms linear models by capturing non-linear price relationships',
            'Median income is the dominant predictor — aligns with real-world economic intuition',
            'Cross-validation ensures results generalize beyond the specific train-test split',
            'System demonstrates data-driven house valuation as a scalable alternative to appraisals',
        ],
        'references': [
            'Pace, R.K. & Barry, R. (1997). Sparse Spatial Autoregressions. Statistics & Probability Letters.',
            'Pedregosa et al. (2011). Scikit-learn: Machine Learning in Python. JMLR 12.',
            'Breiman, L. (2001). Random Forests. Machine Learning, 45(1), 5–32.',
            'Hoerl & Kennard (1970). Ridge Regression: Biased Estimation for Nonorthogonal Problems.',
            'SHAP Team. SHAP — SHapley Additive exPlanations. https://shap.readthedocs.io',
        ],
    },

    # ─────────────────────────────────────────────────────────────────────────
    'expense-tracker-app': {
        'title':    'Personal Expense Tracker Mobile App',
        'subtitle': 'Flutter & SQLite-Based Cross-Platform Finance Management App',
        'domain':   'Mobile Application Development',

        'agenda': [
            'Introduction & Problem Statement', 'Objectives', 'System Architecture',
            'Technology Stack', 'Implementation — UI & State Management',
            'Implementation — SQLite & Data Layer', 'Results & Output',
            'Advantages & Limitations', 'Future Scope', 'Conclusion', 'References',
        ],

        'introduction': {
            'title': 'Introduction & Problem Statement',
            'points': [
                '65% of adults fail to track personal expenses, leading to unintended debt',
                'Existing apps require internet connectivity and cloud accounts — privacy concern',
                'Need for a lightweight, offline-first personal finance tool on mobile',
                'Project: Flutter-based cross-platform app for income/expense tracking',
                'Local SQLite database — data stays on device, no internet required',
                'Features: add transactions, view by category, monthly summary charts',
            ],
        },
        'objectives': {
            'title': 'Objectives of the Project',
            'points': [
                'Build a cross-platform mobile app for Android and iOS using Flutter',
                'Implement SQLite local storage using the sqflite package for offline use',
                'Design an intuitive UI for adding, viewing, editing, and deleting transactions',
                'Categorize transactions (food, transport, utilities, entertainment, salary)',
                'Display monthly summary with category-wise pie charts using fl_chart',
                'Use Provider for state management — update UI in real time as data changes',
            ],
        },
        'architecture': {
            'title': 'System Architecture',
            'points': [
                'UI Layer: Flutter Widgets (StatefulWidget / StatelessWidget)',
                'State: Provider (ChangeNotifier) — notifies widget tree on data change',
                'Business Logic: TransactionProvider calculates totals, filters, categories',
                'Data Layer: DatabaseHelper (singleton) — manages SQLite connection and CRUD',
                'Storage: SQLite file on device (/data/data/com.app/databases/expense.db)',
                'No network layer — fully offline, no backend required',
            ],
        },
        'tech_stack': {
            'title': 'Technology Stack',
            'items': [
                ('Flutter 3.10+', 'Cross-platform UI framework (Android & iOS)'),
                ('Dart',          'Strongly-typed programming language for Flutter'),
                ('sqflite',       'SQLite plugin for Flutter — async local DB operations'),
                ('Provider',      'Lightweight state management with ChangeNotifier'),
                ('fl_chart',      'Pie charts and bar graphs for expense visualization'),
                ('intl',          'Date and currency formatting (₹ / $ / €)'),
            ],
        },
        'module1': {
            'title': 'Implementation — Flutter UI & State Management',
            'points': [
                'HomeScreen: balance summary card + recent transactions ListView',
                'AddTransactionSheet: BottomSheet form with category dropdown, amount, date',
                'CategoryScreen: filter transactions by category with total calculation',
                'ChartsScreen: fl_chart PieChart with category-wise spending breakdown',
                'Provider setup: MultiProvider wraps MaterialApp → TransactionProvider injected',
                'notifyListeners() called after every add/delete → widget rebuilds automatically',
                'Form validation: amount must be positive, description required, date required',
            ],
        },
        'module2': {
            'title': 'Implementation — SQLite Database & Data Layer',
            'points': [
                'DatabaseHelper.instance — singleton ensures one SQLite connection',
                'onCreate: CREATE TABLE transactions (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, amount REAL, category TEXT, date TEXT, type TEXT)',
                'insertTransaction(txn): db.insert() → returns new row id',
                'getAllTransactions(): db.query(orderBy: "date DESC") → List<Map>',
                'deleteTransaction(id): db.delete(where: "id = ?", whereArgs: [id])',
                'Provider.loadTransactions() fetches all rows at app start and on mutation',
                'Balance = sum(INCOME rows) - sum(EXPENSE rows) — computed in Dart',
            ],
        },
        'results': {
            'title': 'Results & Output',
            'points': [
                'App launches in < 1 second — SQLite reads 100 transactions in < 5ms',
                'Add transaction: swipe-up form → save → list refreshes within 50ms',
                'Pie chart updates instantly after adding/deleting a transaction',
                'Monthly balance, total income, and total expense displayed on home screen',
                'Category filter: select "Food" → shows all food expenses with running total',
                'Data persists across app restarts — SQLite file survives device reboot',
                'Tested on Android 12 (emulator) and real device — no layout issues',
            ],
        },
        'advantages': [
            'Fully offline — no internet, no account, no data privacy concern',
            'Single codebase targets both Android and iOS (no Swift/Kotlin needed)',
            'Provider state management is lightweight — no Redux/BLoC boilerplate',
            'sqflite async operations prevent UI freezing on database I/O',
        ],
        'limitations': [
            'Data stored only on device — no sync across multiple phones',
            'No backup — uninstalling or clearing app data permanently erases records',
            'Charts library (fl_chart) limited to basic pie/bar — no trend line charts',
            'No recurring transaction support — every expense must be entered manually',
        ],
        'future_scope': [
            'Add Firebase Firestore sync for cross-device data access',
            'Implement recurring transaction scheduling with local notifications',
            'Export monthly report as PDF or CSV for tax/budgeting purposes',
            'Add budget limits per category with alert notifications on overspend',
            'Biometric lock (fingerprint/face) to protect sensitive financial data',
        ],
        'conclusion': [
            'Delivered a fully functional offline expense tracker for Android and iOS',
            'Flutter + SQLite combination provides fast, reliable local data persistence',
            'Provider state management keeps UI and data layer cleanly separated',
            'App demonstrates real-world mobile development with database integration',
            'Ready for Play Store submission with minor asset and signing configuration',
        ],
        'references': [
            'Flutter Team. Flutter Documentation. https://docs.flutter.dev',
            'sqflite Package. Dart pub.dev. https://pub.dev/packages/sqflite',
            'Provider Package. Remi Rousselet. https://pub.dev/packages/provider',
            'fl_chart Package. Data Visualization for Flutter. https://pub.dev/packages/fl_chart',
            'SQLite Documentation. https://www.sqlite.org/docs.html',
        ],
    },

    # ─────────────────────────────────────────────────────────────────────────
    'network-intrusion-detection': {
        'title':    'Network Intrusion Detection System using XGBoost',
        'subtitle': 'Machine Learning-Based Network Traffic Classification on NSL-KDD',
        'domain':   'Cybersecurity / Machine Learning',

        'agenda': [
            'Introduction & Problem Statement', 'Objectives', 'System Architecture',
            'Technology Stack', 'Implementation — Feature Engineering & Training',
            'Implementation — Detection API & Evaluation', 'Results & Output',
            'Advantages & Limitations', 'Future Scope', 'Conclusion', 'References',
        ],

        'introduction': {
            'title': 'Introduction & Problem Statement',
            'points': [
                'Cyberattacks cost organizations globally $8 trillion in 2023 (Cybersecurity Ventures)',
                'Traditional signature-based IDS fails against novel (zero-day) attacks',
                'Machine learning IDS can detect patterns without predefined attack signatures',
                'Problem: classify network connections as Normal or one of 4 attack types',
                'Dataset: NSL-KDD — improved version of KDD Cup 1999 (125,973 records, 41 features)',
                'Attack classes: DoS, Probe, R2L (Remote-to-Local), U2R (User-to-Root)',
            ],
        },
        'objectives': {
            'title': 'Objectives of the Project',
            'points': [
                'Preprocess NSL-KDD dataset — encode categorical features, handle class imbalance',
                'Train an XGBoost classifier for 5-class intrusion detection',
                'Evaluate using precision, recall, F1-score, and confusion matrix per class',
                'Build a FastAPI endpoint accepting connection features and returning classification',
                'Compare XGBoost against Random Forest and Decision Tree baselines',
                'Analyze feature importance to identify the most discriminative network attributes',
            ],
        },
        'architecture': {
            'title': 'System Architecture',
            'points': [
                'Data: NSL-KDD CSV → Pandas → Label Encoding for protocol_type, service, flag',
                'Preprocessing: StandardScaler normalization → 41 scaled features',
                'Model: XGBoostClassifier (n_estimators=200, max_depth=6, learning_rate=0.1)',
                'Training: 80/20 split → fit on 100,778 samples → evaluate on 25,195',
                'Serialization: joblib.dump(model, "xgb_nids.pkl") for deployment',
                'API: FastAPI POST /detect → load pkl → predict → return label + confidence',
                'Optional: Scapy sniff() for live packet feature extraction → API call',
            ],
        },
        'tech_stack': {
            'title': 'Technology Stack',
            'items': [
                ('Python 3.8+',   'Core language for ML pipeline and API'),
                ('XGBoost',       'Gradient boosting classifier for intrusion detection'),
                ('Scikit-Learn',  'Preprocessing, evaluation metrics, baseline models'),
                ('Pandas / NumPy','Data loading, feature encoding, numerical operations'),
                ('FastAPI',       'REST API to expose the trained model for predictions'),
                ('Scapy',         'Optional: live packet capture for real-time detection'),
            ],
        },
        'module1': {
            'title': 'Implementation — Feature Engineering & Model Training',
            'points': [
                'Load KDDTrain+.txt — 125,973 samples with 41 features + 1 attack label',
                'Label Encoding: protocol_type (TCP/UDP/ICMP), service (21 types), flag (11 types)',
                'Binary label: Normal (0) vs Attack (1) for initial binary model',
                'Multi-class: 5 labels → LabelEncoder (Normal=0, DoS=1, Probe=2, R2L=3, U2R=4)',
                'scale_pos_weight = count(Normal) / count(Attack) — handles class imbalance',
                'XGBoost: n_estimators=200, max_depth=6, learning_rate=0.1, subsample=0.8',
                'Early stopping on validation set — prevents overfitting (best round ~140)',
            ],
        },
        'module2': {
            'title': 'Implementation — API & Evaluation',
            'points': [
                'FastAPI endpoint: POST /detect accepts JSON with 41 network features',
                'Preprocessor pipeline: LabelEncoder + StandardScaler applied at inference',
                'Response: { "prediction": "DoS", "confidence": 0.97, "alert": true }',
                'Classification Report: precision/recall/F1 per class + macro and weighted averages',
                'Confusion matrix: 5×5 heatmap — shows cross-class misclassification patterns',
                'Feature importance: src_bytes, dst_bytes, count, duration top predictors',
                'API tested with Postman — response time < 5ms per connection record',
            ],
        },
        'results': {
            'title': 'Results & Output',
            'points': [
                'Binary (Normal vs Attack): Accuracy 99.2%, F1=0.993',
                'Multi-class XGBoost: Overall Accuracy 98.7%, Macro F1=0.962',
                'DoS detection: Precision 99.8%, Recall 99.5% — highest performing class',
                'U2R detection: F1=0.84 — smallest class, hardest to classify (4% of data)',
                'XGBoost outperforms Random Forest (97.1%) and Decision Tree (95.3%)',
                'Feature importance: src_bytes (18%), dst_bytes (14%), count (11%)',
                'API inference: < 5ms per sample — suitable for real-time network monitoring',
            ],
        },
        'advantages': [
            'XGBoost achieves 98.7% accuracy without any handcrafted signatures',
            'Generalizes to attack types not seen during training (anomaly behavior)',
            'FastAPI deployment enables integration into existing network monitoring tools',
            'Feature importance output guides security teams on what to monitor',
        ],
        'limitations': [
            'NSL-KDD is a 1999-era dataset — modern attack vectors may not be represented',
            'U2R class severely underrepresented — model biased toward majority classes',
            'Static model — requires periodic retraining as new attack patterns emerge',
            'Does not handle encrypted (HTTPS/TLS) traffic — metadata only',
        ],
        'future_scope': [
            'Train on modern datasets: CICIDS-2017, UNSW-NB15 for contemporary attacks',
            'Add online learning — model updates incrementally from new traffic data',
            'Deploy with Scapy for real-time packet-level detection on live networks',
            'Add SHAP explanations for each detection — "why was this flagged as DoS?"',
            'Extend to detect DDoS in encrypted traffic using flow-level features (Argus)',
        ],
        'conclusion': [
            'Built an ML-based IDS achieving 98.7% accuracy on the NSL-KDD benchmark',
            'XGBoost gradient boosting significantly outperforms traditional rule-based IDS',
            'FastAPI endpoint enables seamless integration into SOC monitoring workflows',
            'Feature importance analysis reveals that byte counts are the strongest attack indicators',
            'Provides a scalable foundation for AI-driven network security systems',
        ],
        'references': [
            'Tavallaee, M. et al. (2009). A Detailed Analysis of the KDD CUP 99 Data Set. IEEE CISDA.',
            'Chen, T. & Guestrin, C. (2016). XGBoost: A Scalable Tree Boosting System. ACM SIGKDD.',
            'NIST (2023). Guide to Intrusion Detection and Prevention Systems. SP 800-94 Rev. 1.',
            'Scikit-Learn. Classification Metrics. https://scikit-learn.org/stable/modules/model_evaluation',
            'Scapy Team. Scapy Documentation. https://scapy.readthedocs.io',
        ],
    },

    # ─────────────────────────────────────────────────────────────────────────
    'face-recognition-attendance': {
        'title':    'Automated Face Recognition Attendance System',
        'subtitle': 'Real-Time Attendance Marking using dlib, OpenCV & Flask',
        'domain':   'Computer Vision / Web Application',

        'agenda': [
            'Introduction & Problem Statement', 'Objectives', 'System Architecture',
            'Technology Stack', 'Implementation — Face Registration & Recognition',
            'Implementation — Flask Dashboard & SQLite', 'Results & Output',
            'Advantages & Limitations', 'Future Scope', 'Conclusion', 'References',
        ],

        'introduction': {
            'title': 'Introduction & Problem Statement',
            'points': [
                'Manual attendance is time-consuming and prone to proxy marking fraud',
                'Biometric fingerprint systems are expensive and require physical contact',
                'Face recognition is contactless, fast, and works with standard webcams',
                'Project: real-time attendance via webcam using dlib 128-D face encodings',
                'System marks attendance to SQLite DB and displays dashboard via Flask',
                'Each student recognized in < 200ms per frame at standard webcam resolution',
            ],
        },
        'objectives': {
            'title': 'Objectives of the Project',
            'points': [
                'Implement real-time face detection and recognition using dlib + OpenCV',
                'Register student faces once — generate 128-D encodings for each student',
                'Compare live frame encodings against stored encodings for identification',
                'Mark attendance to SQLite database with name, date, time (once per day)',
                'Build a Flask web dashboard for viewing, filtering, and exporting attendance',
                'Handle multiple faces in a single frame for classroom deployment',
            ],
        },
        'architecture': {
            'title': 'System Architecture',
            'points': [
                'Registration: webcam frame → dlib detect face → compute 128-D encoding → save to .pkl',
                'Recognition: live frame → resize to 25% → detect faces → compute encodings',
                'Matching: face_recognition.compare_faces(known_encodings, live_encoding, tolerance=0.6)',
                'Attendance: if match → INSERT to SQLite (name, date, time) — skip if already marked today',
                'Flask API: GET /attendance → query SQLite → render HTML table (Jinja2)',
                'OpenCV: draw rectangle + name label on matched face in live feed',
            ],
        },
        'tech_stack': {
            'title': 'Technology Stack',
            'items': [
                ('Python 3.10+',       'Core language (3.10 recommended for dlib compatibility)'),
                ('face_recognition',   'dlib wrapper — face detection + 128-D encodings'),
                ('OpenCV',             'Webcam capture, frame processing, UI overlay'),
                ('dlib',               'HOG-based face detector + ResNet face encoder'),
                ('Flask',              'Web framework for attendance dashboard and API'),
                ('SQLite',             'Lightweight local database for attendance records'),
            ],
        },
        'module1': {
            'title': 'Implementation — Face Registration & Real-Time Recognition',
            'points': [
                'register.py: webcam captures 5 photos per student → face_recognition.face_encodings()',
                'Encodings stored: pickle.dump({"name": [encoding1, encoding2, ...]}, file)',
                'recognition.py: cap = cv2.VideoCapture(0) → read frame in loop',
                'Resize frame to 25% → face_recognition.face_locations() (HOG model)',
                'face_recognition.face_encodings() for each detected face in small frame',
                'compare_faces(known_encodings, face_encoding) → boolean array → argmin distance',
                'Identified name drawn with cv2.rectangle() and cv2.putText() on full-res frame',
            ],
        },
        'module2': {
            'title': 'Implementation — Attendance DB & Flask Dashboard',
            'points': [
                'SQLite schema: CREATE TABLE attendance (id, name TEXT, date TEXT, time TEXT)',
                'Before INSERT: SELECT count WHERE name=? AND date=today → skip if >0',
                'Flask route GET /attendance: query all records → pass to Jinja2 template',
                'HTML table: date filter, name search, "Export CSV" button',
                'GET /attendance/export: pd.read_sql() → StringIO CSV → send_file response',
                'GET /attendance/today: filter by today\'s date → show live class attendance',
                'Admin can delete erroneous records via DELETE /attendance/<id>',
            ],
        },
        'results': {
            'title': 'Results & Output',
            'points': [
                'Face registration: 5 photos per student, encoding stored in < 2 seconds',
                'Recognition accuracy: 96.8% on 15-student test set (good lighting)',
                'Processing speed: 8–12 FPS on CPU at 1080p with 25% resize optimization',
                'Attendance marked within 200ms of face recognition — near real-time',
                'Duplicate prevention: second scan of same student on same day skipped',
                'Flask dashboard loads attendance table in < 100ms for 1,000 records',
                'CSV export works for any date range — tested with 3 months of records',
            ],
        },
        'advantages': [
            'Contactless — hygienic, no physical interaction required (post-COVID relevant)',
            'Handles multiple faces simultaneously — entire classroom in one scan',
            'Flask dashboard accessible from any device on the local network',
            'SQLite requires zero server setup — single .db file, portable',
        ],
        'limitations': [
            'Performance degrades in poor lighting, extreme angles, or with face masks',
            'Photos can spoof the system — no liveness detection implemented',
            'Recognition accuracy drops below 90% for twins or very similar-looking students',
            'dlib installation on Windows requires cmake and Visual C++ Build Tools',
        ],
        'future_scope': [
            'Add blink detection for liveness — prevents photo spoofing attacks',
            'Deploy to Raspberry Pi with camera module for embedded classroom installation',
            'Migrate to cloud database (PostgreSQL) for multi-classroom, multi-branch setup',
            'Build mobile app for real-time attendance notification to parents/admin',
            'Use MTCNN or RetinaFace for better face detection accuracy in low light',
        ],
        'conclusion': [
            'Built an end-to-end automated attendance system using computer vision',
            'dlib 128-D face encodings provide robust identity matching across lighting conditions',
            'OpenCV optimizations (25% resize) maintain real-time performance on CPU',
            'Flask dashboard provides a clean, web-based attendance management interface',
            'System eliminates proxy attendance and reduces manual marking overhead',
        ],
        'references': [
            'King, D.E. (2009). Dlib-ml: A Machine Learning Toolkit. Journal of Machine Learning Research.',
            'Amos, B. et al. (2016). OpenFace: A General-purpose Face Recognition Library. CMU.',
            'Bradski, G. (2000). The OpenCV Library. Dr. Dobb\'s Journal of Software Tools.',
            'Flask Documentation. https://flask.palletsprojects.com',
            'SQLite Documentation. https://www.sqlite.org/docs.html',
        ],
    },

    # ─────────────────────────────────────────────────────────────────────────
    'library-management': {
        'title':    'Library Management System',
        'subtitle': 'Spring Boot & JPA/Hibernate REST API with MySQL Backend',
        'domain':   'Enterprise Java / Database Systems',

        'agenda': [
            'Introduction & Problem Statement', 'Objectives', 'System Architecture',
            'Technology Stack', 'Implementation — Spring Boot API & JPA Entities',
            'Implementation — Business Logic & Security', 'Results & Output',
            'Advantages & Limitations', 'Future Scope', 'Conclusion', 'References',
        ],

        'introduction': {
            'title': 'Introduction & Problem Statement',
            'points': [
                'Manual library record-keeping is error-prone and fails to scale with demand',
                'Paper-based systems lack real-time availability checking and fine tracking',
                'Need for a digitized system covering catalog, members, and book issuance',
                'Project: Spring Boot REST API + JPA/Hibernate + MySQL for complete automation',
                'Features: book CRUD, member management, issue/return, fine calculation',
                'Hibernate auto-generates the MySQL schema from Java entity classes',
            ],
        },
        'objectives': {
            'title': 'Objectives of the Project',
            'points': [
                'Design a normalized MySQL schema for books, members, and issuances',
                'Build Spring Boot REST API with full CRUD for all library entities',
                'Use JPA/Hibernate ORM — no raw SQL, entity classes map to DB tables',
                'Implement business logic: issue book (decrement copies), return (fine calc)',
                'Enforce data integrity with @Transactional on multi-step operations',
                'Add Spring Security HTTP Basic auth to protect admin endpoints',
            ],
        },
        'architecture': {
            'title': 'System Architecture',
            'points': [
                'Client: REST client (Postman / browser) → HTTP requests on port 8080',
                'Controller Layer: @RestController — maps HTTP routes to service calls',
                'Service Layer: @Service — business logic (issueBook, calculateFine)',
                'Repository Layer: @Repository extends JpaRepository — CRUD auto-generated',
                'Entity Layer: @Entity classes (Book, Member, Issuance) → Hibernate creates tables',
                'Database: MySQL 8.0 — Hibernate DDL auto=update creates/alters tables',
            ],
        },
        'tech_stack': {
            'title': 'Technology Stack',
            'items': [
                ('Java 17',             'Programming language (LTS version)'),
                ('Spring Boot 3.x',     'Application framework with auto-configuration'),
                ('Spring Data JPA',     'Repository abstraction over Hibernate ORM'),
                ('Hibernate',           'JPA implementation — ORM and schema generation'),
                ('MySQL 8.0',           'Relational database for production data storage'),
                ('Maven',               'Dependency management and build lifecycle'),
            ],
        },
        'module1': {
            'title': 'Implementation — Spring Boot API & JPA Entities',
            'points': [
                '@Entity Book: id (auto-generated), title, author, isbn, totalCopies, availableCopies',
                '@Entity Member: id, name, email (@Column unique=true), phone, joinDate',
                '@Entity Issuance: id, @ManyToOne book, @ManyToOne member, issueDate, dueDate, returnDate, fine',
                'BookRepository extends JpaRepository<Book, Long> — findByIsbn(), findByTitleContaining()',
                'application.properties: spring.datasource.url, username, password, ddl-auto=update',
                'GET /books — list all | POST /books — create | PUT /books/{id} | DELETE /books/{id}',
                'GET /members/{id}/history — all issuances for a member with JOIN FETCH',
            ],
        },
        'module2': {
            'title': 'Implementation — Business Logic & Transaction Management',
            'points': [
                'POST /issue — @Transactional: check availableCopies > 0 → decrement → create Issuance',
                'POST /return/{issuanceId} — set returnDate, calculate fine (₹2/day overdue)',
                '@Transactional ensures: if Issuance insert fails → copy count rolled back',
                'Fine calculation: if (returnDate > dueDate) fine = DAYS_BETWEEN × 2 else 0',
                'Spring Security: BasicAuth — LIBRARIAN role required for issue/return endpoints',
                'Global exception handler: @ControllerAdvice returns structured JSON errors',
                'Pagination: GET /books?page=0&size=10 via Pageable parameter in repository',
            ],
        },
        'results': {
            'title': 'Results & Output',
            'points': [
                'Hibernate creates all 3 tables automatically on first application startup',
                'Book issuance: POST /issue → availableCopies decrements atomically in < 20ms',
                'Return with fine: overdue 5 days → fine = ₹10 calculated and stored correctly',
                'Spring Data JPA query: 1,000-book library catalog filtered by title in < 15ms',
                'Concurrent issuance test: simultaneous requests correctly handle last-copy edge case',
                'Spring Security blocks unauthorized DELETE /books without LIBRARIAN credentials',
                'API documented automatically via Swagger UI at http://localhost:8080/swagger-ui',
            ],
        },
        'advantages': [
            'JPA eliminates boilerplate SQL — 80% less database code vs raw JDBC',
            '@Transactional ensures data consistency across multi-step operations',
            'Spring Boot auto-configuration reduces setup time from days to minutes',
            'Schema auto-generation via Hibernate — no manual CREATE TABLE scripts needed',
        ],
        'limitations': [
            'ddl-auto=update is unsafe in production — requires Flyway migration scripts',
            'HTTP Basic auth transmits credentials on every request — use JWT in production',
            'N+1 query problem if issuances are loaded eagerly without JOIN FETCH',
            'MySQL single-server setup has no high-availability failover',
        ],
        'future_scope': [
            'Migrate to Flyway for versioned, production-safe database schema migrations',
            'Add JWT authentication with role-based access (LIBRARIAN, MEMBER, ADMIN)',
            'Build React frontend for librarian dashboard and member self-service portal',
            'Send email notifications for due-date reminders and overdue alerts (JavaMail)',
            'Add barcode scanning via ZXing library for faster book check-in/check-out',
        ],
        'conclusion': [
            'Delivered a full-featured library management REST API using enterprise Java stack',
            'JPA/Hibernate ORM provides clean, maintainable data access with zero SQL boilerplate',
            '@Transactional annotation ensures ACID compliance for critical issuance operations',
            'Spring Boot reduces infrastructure setup time while enabling production-grade features',
            'System is immediately deployable and extensible for real library use cases',
        ],
        'references': [
            'Walls, C. (2022). Spring Boot in Action (2nd Ed.). Manning Publications.',
            'Bauer, C. et al. (2015). Java Persistence with Hibernate (2nd Ed.). Manning.',
            'Spring Team. Spring Data JPA Documentation. https://spring.io/projects/spring-data-jpa',
            'MySQL 8.0 Reference Manual. https://dev.mysql.com/doc/refman/8.0',
            'Baeldung. Spring Boot Tutorials. https://www.baeldung.com',
        ],
    },
}
